name: react-native-android-build-apk
on:
    push:
        branches:
            - bare
            - production
jobs:
    build-android:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            - name: prepare env file
              env:
                  GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}
                  GOOGLE_EXPO_CLIENT_ID: ${{ secrets.GOOGLE_EXPO_CLIENT_ID }}
                  GOOGLE_IOS_CLIENT_ID: ${{ secrets.GOOGLE_IOS_CLIENT_ID }}
                  GOOGLE_ANDROID_CLIENT_ID: ${{ secrets.GOOGLE_ANDROID_CLIENT_ID }}
                  GOOGLE_WEB_CLIENT_ID: ${{ secrets.GOOGLE_WEB_CLIENT_ID }}
              run: |
                  echo GRAPHQL_ENDPOINT="$GRAPHQL_ENDPOINT" >> .env
                  echo GOOGLE_EXPO_CLIENT_ID="$GOOGLE_EXPO_CLIENT_ID" >> .env
                  echo GOOGLE_IOS_CLIENT_ID="$GOOGLE_IOS_CLIENT_ID" >> .env
                  echo GOOGLE_ANDROID_CLIENT_ID="$GOOGLE_ANDROID_CLIENT_ID" >> .env
                  echo GOOGLE_WEB_CLIENT_ID="$GOOGLE_WEB_CLIENT_ID" >> .env
            - name: prepare gradle.properties file
              env:
                  MYAPP_UPLOAD_STORE_FILE: ${{ secrets.GRAPHQL_ENDPOINT }}
                  MYAPP_UPLOAD_KEY_ALIAS: ${{ secrets.GOOGLE_EXPO_CLIENT_ID }}
                  MYAPP_UPLOAD_STORE_PASSWORD: ${{ secrets.GOOGLE_IOS_CLIENT_ID }}
                  MYAPP_UPLOAD_KEY_PASSWORD: ${{ secrets.GOOGLE_ANDROID_CLIENT_ID }}
              run: |
                  echo MYAPP_UPLOAD_STORE_FILE="$MYAPP_UPLOAD_STORE_FILE" >> ./android/gradle.properties
                  echo MYAPP_UPLOAD_KEY_ALIAS="$MYAPP_UPLOAD_KEY_ALIAS" >> ./android/gradle.properties
                  echo MYAPP_UPLOAD_STORE_PASSWORD="$MYAPP_UPLOAD_STORE_PASSWORD" >> ./android/gradle.properties
                  echo MYAPP_UPLOAD_KEY_PASSWORD="$MYAPP_UPLOAD_KEY_PASSWORD" >> ./android/gradle.properties
            - name: prepare sign key
              env:
                  MYAPP_UPLOAD_STORE_FILE_ENCRYPTED: ${{ secrets.MYAPP_UPLOAD_STORE_FILE_ENCRYPTED }}
                  MYAPP_UPLOAD_STORE_FILE: ${{ secrets.MYAPP_UPLOAD_STORE_FILE }}
              run: |
                  cat "$MYAPP_UPLOAD_STORE_FILE_ENCRYPTED" | base64 --decode > ./android/app/"$MYAPP_UPLOAD_STORE_FILE".jks
            - name: Build Android Release
              run: |
                  cd android && ./gradlew assembleRelease
            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: app-release.apk
                  path: android/app/build/outputs/apk/release/
